spring:
  # Database
  datasource:
    url: jdbc:postgresql://postgres-db:5432/ecommerce_db
    username: postgres
    password: "012345"
    driver-class-name: org.postgresql.Driver
    # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  data:
    redis:
      host: redis-server
      port: 6379